apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-euh7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-euh7
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-euh7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-euh7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-euh7
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nakc-tenant/rhtap-demo-app/hacbs-test-project-euh7@sha256:30c7028a8b2aea5b5ea5ed4d4e8c2768f9da93aa9725a7ce2e44baca51fbdaf6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
